version: '3'
services:
  mysql-db:
    image: mysql:latest
    container_name: docker-compose-mysql-db-2
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=achatdb
   
  spring-boot-app:
    image: ikbel436/achat
    container_name: docker-compose-spring-boot-1
    ports:
      - "8089:8080"
    depends_on:
      - mysql-db
  
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://docker-compose-mysql-db-1:3306/achatdb?&createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  angular-app:
    image: ikbel436/frontachat
    container_name: front_achat
    ports:
      - "4200:80"
    depends_on:
      - spring-boot-app
   